baseURL = "/"
languageCode = "pt-br"
title = "Lelolabs"
theme = "kube"
description = "Redes, Linux, Servidores, Automação, Xcode, iOS, macOS"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "Aurélio Carlos" # add your company name
  github = "lelinho" # add your github profile name
  twitter = "lelinhoprado" # add your twitter profile
  email = "aureliocarlosps@gmail.com"

[[menu.main]]
    name = "Projetos"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"