baseURL = "/"
languageCode = "pt-br"
title = "Lelolabs"
theme = "anatole"
description = "Redes, Linux, Servidores, Automação, Xcode, iOS, macOS"
Paginate = 4
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true


[params]
  title = "Aurélio Carlos"
  RSSLink = "/index.xml"
  author = "Aurélio Carlos"
  favicon = "img/lelolabs.png"

  #github = "lelinho" # add your github profile name
  #twitter = "lelinhoprado" # add your twitter profile
  email = "aureliocarlosps@gmail.com"

  description = "(lelinhoprado)"
  profilePicture = "img/profile_pic.JPG"
  doNotLoadAnimations = false
  gtagId = "G-B6RGXS41JS"

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/aurelio-c-a9621b1b9/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/lelinho"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/lelinhoprado"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:aureliocarlosps@gmail.com"


[[menu.main]]
    name = "Projetos"
    weight = -99
    url = "/projetos/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/"
[[menu.main]]
    name = "Sobre"
    weight = -98
    url = "/about/"
[[menu.main]]
    name = "Currículo"
    weight = -97
    url = "https://github.com/lelinho/curriculo_Aurelio/releases/download/v0.0-rolling/curriculo.pdf"

[deployment]
[[deployment.targets]]
# An arbitrary name for this target.
name = "lelolabs"

# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://lelolabs.com?region=us-east-2"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
cloudFrontDistributionID = "E1SJ1LU1L0IICT"